workdir: "../.." # With this we can specify where should Snakemake look for things relative to this path


rule rename_array:
    input:
        "data/raw/array.npy"
    output:
        "data/processed/array_renamed.npy"
    shell:
        "python ../scripts/rename_array.py {input[0]} {output[0]}"

rule standardize_renamed_array:
    input: "data/processed/renamed_array.npy"
    output: "data/processed/renamed_array_standardized.npy"
    run:
        import numpy as np
        arr = np.load(input[0])
        output_arr = arr*5
        np.save(output[0],output_arr)


rule combine_array:
    input:
        "data/raw/array1.npy",
        "data/raw/array2.npy"
    output:
        "data/processed/combined_array.npy"
    run:
        import numpy as np
        array1 = np.load(input[0])
        array2 = np.load(input[1])
        data = np.concatenate((array1, array2))
        reshape_array = data.reshape(-1,2)
        np.save(output[0],reshape_array) 

rule combine_array_standardized:
    input:
        "data/processed/combined_array.npy"
    output:
        "data/processed/combined_array_standardized.npy"
    run:
        import numpy as np
        data = np.load(input[0])
        standardized = (data - np.mean(data))/np.std(data)
        np.save(output[0],standardized)

rule combine_array_normalized:
    input:
        "data/processed/combined_array.npy"
    output:
        "data/processed/combined_array_normalized.npy"
    shell:
        "python /workspace/iBOTS-Developing-Data-Analysis-Projects/session4/scripts/normalize_array.py {input[0]} {output[0]}"

rule valid_trials:
    input:
        "data/raw/session.csv"
    output:
        "data/processed/session_valid.csv"
    shell:
        "python scripts/extract_valid_trials.py {input[0]} {output[0]}"
    
rule correct_response:
    input:
        "data/processed/session_valid.csv"
    output:
        "data/processed/session_valid_correct_response.csv"
    shell:
        "python scripts/response.py {input[0]} {output[0]}"


